graph LR

classDef subgraph_padding fill:none,stroke:none

  subgraph org1_example_com [Organization: Org1<br>org1.example.com]
    subgraph org1_example_com_padding [ ]
      direction RL
      subgraph ord_group_group1_orderer0_group1_org1_example_com [Orderer Group: group1<br>etcdraft]
        subgraph ord_group_group1_orderer0_group1_org1_example_com_padding [ ]
          direction RL
          orderer0_group1_org1_example_com[orderer0.group1.org1.example.com]
        end
        class ord_group_group1_orderer0_group1_org1_example_com_padding subgraph_padding
      end
      ca_org1_example_com([ca.org1.example.com<br>sqlite])
      peer0_org1_example_com[peer0.org1.example.com<br>LevelDb]
    end
    class org1_example_com_padding subgraph_padding
  end

  subgraph channel_my_channel1 [Channel: my-channel1]
    subgraph channel_my_channel1_padding [ ]
      channel_my_channel1_empty[" "]
      style channel_my_channel1_empty fill:#ffffff00,stroke:#ffffff00
    end
    class channel_my_channel1_padding subgraph_padding
  end

  %% Connections
  peer0_org1_example_com --> channel_my_channel1
  channel_my_channel1 --> ord_group_group1_orderer0_group1_org1_example_com